linters:

  ClassesBeforeIds:
    enabled: false

  ConsecutiveComments:
    enabled: false

  IdNames:
    enabled: false

  RepeatedId:
    enabled: false

  InlineStyles:
    enabled: false

  InstanceVariables:
    enabled: false

  LeadingCommentSpace:
    enabled: false

  LineLength:
    enabled: false

  ObjectReferenceAttributes:
    enabled: false

  SpaceInsideHashAttributes:
    enabled: false

  UnnecessaryStringOutput:
    enabled: false

  ViewLength:
    enabled: false
