AllCops:
  TargetRubyVersion: 2.3
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'specs/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'cookbooks/**/*'
    - 'db/**/*.rb'
    - 'lib/geolocal.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

###############################################################################
#                              L A Y O U T                                    #
###############################################################################
Layout/AlignArray:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/RescueException:
  Enabled: false

###############################################################################
#                              M E T R I C S                                  #
###############################################################################
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 2000

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/LineLength:
  Max: 1000

Metrics/MethodLength:
  Max: 500

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

###############################################################################
#                              N A M I N G                                    #
###############################################################################
Naming/AccessorMethodName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

###############################################################################
#                            P E R F O R M A N C E                            #
###############################################################################
Performance/Count:
  Enabled: false

Performance/Detect:
  Enabled: false

###############################################################################
#                                  R A I L S                                  #
###############################################################################
Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Rails/Validation:
  Enabled: false

###############################################################################
#                             S E C U R I T Y                                 #
###############################################################################
Security/Eval:
  Enabled: false

###############################################################################
#                                 S T Y L E                                   #
###############################################################################
Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/OneLineConditional:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
