require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'specs/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*.rb'
  NewCops: enable
  SuggestExtensions: false

# --------------------------------------------------------------------------- #
#                              L A Y O U T                                    #
# --------------------------------------------------------------------------- #
Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 2000

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

# --------------------------------------------------------------------------- #
#                              M E T R I C S                                  #
# --------------------------------------------------------------------------- #
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 9

Metrics/ClassLength:
  Max: 2000

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/MethodLength:
  Max: 500

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

# --------------------------------------------------------------------------- #
#                              N A M I N G                                    #
# --------------------------------------------------------------------------- #
Naming/AccessorMethodName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# --------------------------------------------------------------------------- #
#                                  R A I L S                                  #
# --------------------------------------------------------------------------- #
Rails:
  Enabled: true

Rails/ContentTag:
  Enabled: false

Rails/DuplicateScope:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Rails/Validation:
  Enabled: false

# --------------------------------------------------------------------------- #
#                             S E C U R I T Y                                 #
# --------------------------------------------------------------------------- #
Security/Eval:
  Enabled: false

Security/Open:
  Enabled: false

# --------------------------------------------------------------------------- #
#                                 S T Y L E                                   #
# --------------------------------------------------------------------------- #
Style/AccessorGrouping:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/OneLineConditional:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
