development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: stardate_production

# <%
#   path = File.join Rails.root, 'config', 'redis.yml'

#   if File.exist?(path)
#     config = YAML.load_file(File.open(path))[Rails.env]
#   else
#     config = {}
#     config['host'] = 'localhost'
#     config['port'] = '6379'
#   end
# %>

# default: &default
#   adapter: redis
#   url: redis://<%= config['host'] %>:<%= config['port'] %>/1
#   channel_prefix: vocal_<%= Rails.env %>

# development:
#   <<: *default

# test:
#   adapter: async

# production:
#   <<: *default
