<%
  path = File.join Rails.root, 'config', 'redis.yml'

  if File.exist?(path)
    config = YAML.load_file(File.open(path))[Rails.env]
  else
    config = {}
    config['host'] = 'localhost'
    config['port'] = '6379'
  end
%>

default: &default
  adapter: redis
  url: redis://<%= config['host'] %>:<%= config['port'] %>/1
  channel_prefix: vocal_<%= Rails.env %>

development:
  <<: *default

production:
  <<: *default
