default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: vocal_<%= Rails.env %>

development:
  <<: *default

production:
  <<: *default
