# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "items", :force => true do |t|
    t.integer "user_id"
    t.integer "category_id"
    t.date    "date"
    t.integer "value"
    t.text    "description"
  end

  add_index "items", ["user_id"], :name => "index_items_on_user_id"
  add_index "items", ["date"], :name => "index_items_on_date"

  create_table "jobs", :force => true do |t|
    t.integer  "user_id"
    t.string   "name"
    t.boolean  "active",                                   :default => true
    t.datetime "created_at"
    t.decimal  "rate",       :precision => 6, :scale => 2
  end

  add_index "jobs", ["user_id"], :name => "index_projects_on_user_id"

  create_table "paychecks", :force => true do |t|
    t.integer  "job_id"
    t.integer  "item_id"
    t.datetime "created_at"
    t.string   "description"
    t.decimal  "value",       :precision => 8, :scale => 2
  end

  add_index "paychecks", ["job_id"], :name => "index_paychecks_on_job_id"
  add_index "paychecks", ["item_id"], :name => "index_paychecks_on_item_id"

  create_table "recurrings", :force => true do |t|
    t.integer "user_id"
    t.integer "category_id"
    t.integer "day"
    t.integer "value"
    t.text    "description"
  end

  add_index "recurrings", ["user_id"], :name => "index_recurrings_on_user_id"
  add_index "recurrings", ["day"], :name => "index_recurrings_on_day"

  create_table "taggings", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "tag_id"
    t.integer  "item_id"
  end

  create_table "tags", :force => true do |t|
    t.string "name"
  end

  create_table "tasks", :force => true do |t|
    t.integer  "job_id"
    t.datetime "created_at"
    t.date     "date"
    t.integer  "minutes"
    t.string   "description"
    t.integer  "paycheck_id"
  end

  add_index "tasks", ["job_id"], :name => "index_tasks_on_project_id"
  add_index "tasks", ["paycheck_id"], :name => "index_tasks_on_paycheck_id"

  create_table "users", :force => true do |t|
    t.string   "email",         :default => "",                    :null => false
    t.string   "password_salt", :default => "",                    :null => false
    t.string   "password_hash", :default => "",                    :null => false
    t.string   "time_zone"
    t.datetime "created_at",    :default => '2007-05-24 15:49:54'
  end

  add_index "users", ["email"], :name => "index_users_on_email"

end
